name: Generate flyingbird-clash rules(mixed)
run-name: ${{ github.actor }} is trigger generation 🚀
on: 
  push:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  generate-flyingbird-clash-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup AWS Cli Action
        uses: warjiang/setup-awscli-action@v0.1.1
      - name: Setup AWS config
        run: |
          mkdir -p ~/.aws
          echo "${{ vars.AWS_CREDENTIALS }}" > ~/.aws/credentials
          echo "${{ vars.AWS_CONFIG }}" > ~/.aws/config
          mkdir -p dist
      - name: Test AWS config
        run: |
          aws --version
          aws --profile qiniu s3 ls
      - name: Generate And Upload Rules
        run: |
          SHELL_FOLDER=$(pwd)
          SUBSCRIBE_LINK="${{ vars.FLYINGBIRD_SUBSCRIBE_LINK }}"
          IFS='#' read -r -a array <<< "$SUBSCRIBE_LINK"
          subscribe_link=${array[0]}
          profile=${array[1]}
          target_path=${array[2]}
          wget "$subscribe_link" -O clash.yaml
          aws --profile ${profile} s3 cp --acl public-read ./clash.yaml ${$target_path}
